#!/bin/bash

# A bash script to run $1 iterations of the cleaning script for experimentation
# Author: Adam Shelton

for i in $(seq "$1"); do
    mpiexec -n 1 python3 cleaning_MPI.py Badges.xml
    mpiexec -n 2 python3 cleaning_MPI.py Badges.xml
    mpiexec -n 4 python3 cleaning_MPI.py Badges.xml
    mpiexec -n 8 python3 cleaning_MPI.py Badges.xml
    mpiexec -n 16 python3 cleaning_MPI.py Badges.xml
    mpiexec --hostfile hosts -n 16 python3 cleaning_MPI.py Badges.xml
    # MPI prioritizes less hosts over less nodes per host, so running on four hosts needs to be run separately,
    #   so each host actually runs four nodes instead od just repeating the previous test
    #mpiexec --hostfile hosts4 -n 16 python3 cleaning_MPI.py Badges.xml
done
